const id = 1;

const colors = {
  primary: '#006c50',
  onPrimary: '#ffffff',
  primaryContainer: '#84f8cd',
  onPrimaryContainer: '#002116',
  primaryFixed: '#84f8cd',
  onPrimaryFixed: '#002116',
  primaryFixedDim: '#66dbb1',
  onPrimaryFixedVariant: '#00513c',
  secondary: '#4c6359',
  onSecondary: '#ffffff',
  secondaryContainer: '#cee9db',
  onSecondaryContainer: '#082017',
  secondaryFixed: '#cee9db',
  onSecondaryFixed: '#082017',
  secondaryFixedDim: '#b3ccbf',
  onSecondaryFixedVariant: '#354c42',
  tertiary: '#3f6375',
  onTertiary: '#ffffff',
  tertiaryContainer: '#c2e8fd',
  onTertiaryContainer: '#001f2a',
  tertiaryFixed: '#c2e8fd',
  onTertiaryFixed: '#001f2a',
  tertiaryFixedDim: '#a6cce0',
  onTertiaryFixedVariant: '#264b5c',
  error: '#ba1a1a',
  errorContainer: '#ffdad6',
  onError: '#ffffff',
  onErrorContainer: '#410002',
  background: '#fbfdf9',
  onBackground: '#191c1a',
  outline: '#707974',
  inverseOnSurface: '#eff1ee',
  inverseSurface: '#2e312f',
  inversePrimary: '#66dbb1',
  shadow: '#000000',
  surfaceTint: '#006c50',
  outlineVariant: '#bfc9c2',
  scrim: '#000000',
  surface: '#f8faf6',
  onSurface: '#191c1a',
  surfaceVariant: '#dbe5de',
  onSurfaceVariant: '#404944',
  surfaceContainerHighest: '#e1e3e0',
  surfaceContainerHigh: '#e6e9e5',
  surfaceContainer: '#eceeeb',
  surfaceContainerLow: '#f2f4f1',
  surfaceContainerLowest: '#ffffff',
  surfaceDim: '#d8dbd7',
  surfaceBright: '#f8faf6',
};

const android = {
  colorAccentPrimary: '#84f8cd',
  colorAccentPrimaryVariant: '#006c50',
  colorAccentSecondary: '#cee9db',
  colorAccentSecondaryVariant: '#4c6359',
  colorAccentTertiary: '#c2e8fd',
  colorAccentTertiaryVariant: '#3f6375',
  textColorPrimary: '#191c1a',
  textColorSecondary: '#404944',
  textColorTertiary: '#707974',
  textColorPrimaryInverse: '#eff1ee',
  textColorSecondaryInverse: '#c5c7c4',
  textColorTertiaryInverse: '#8e918e',
  colorBackground: '#eff1ee',
  colorBackgroundFloating: '#f8faf6',
  colorSurface: '#f8faf6',
  colorSurfaceVariant: '#e1e3e0',
  colorSurfaceHighlight: '#ffffff',
  surfaceHeader: '#e1e3e0',
  underSurface: '#000000',
  offState: '#2e312f',
  accentSurface: '#e9f3ec',
  textPrimaryOnAccent: '#191c1a',
  textSecondaryOnAccent: '#404944',
  volumeBackground: '#393c3a',
  scrim: '#c5c7c4',
};

const fonts = {
  body: {
    large: {
      fontFamilyName: 'Roboto',
      fontFamilyStyle: 'Regular',
      fontWeight: 400,
      fontSize: 16,
      letterSpacing: 0.5,
    },
    medium: {
      fontFamilyName: 'Roboto',
      fontFamilyStyle: 'Regular',
      fontWeight: 400,
      fontSize: 14,
      letterSpacing: 0.25,
    },
    small: {
      fontFamilyName: 'Roboto',
      fontFamilyStyle: 'Regular',
      fontWeight: 400,
      fontSize: 12,
      letterSpacing: 0.4000000059604645,
    },
  },
  label: {
    large: {
      fontFamilyName: 'Roboto',
      fontFamilyStyle: 'Medium',
      fontWeight: 500,
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.10000000149011612,
    },
    medium: {
      fontFamilyName: 'Roboto',
      fontFamilyStyle: 'Medium',
      fontWeight: 500,
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.5,
    },
    small: {
      fontFamilyName: 'Roboto',
      fontFamilyStyle: 'Medium',
      fontWeight: 500,
      fontSize: 11,
      lineHeight: 16,
      letterSpacing: 0.5,
    },
  },
  title: {
    large: {
      fontFamilyName: 'Roboto',
      fontFamilyStyle: 'Regular',
      fontWeight: 400,
      fontSize: 22,
      lineHeight: 28,
      letterSpacing: 0,
    },
    medium: {
      fontFamilyName: 'Roboto',
      fontFamilyStyle: 'Medium',
      fontWeight: 500,
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0.15000000596046448,
    },
    small: {
      fontFamilyName: 'Roboto',
      fontFamilyStyle: 'Medium',
      fontWeight: 500,
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.10000000149011612,
    },
  },
};

const size = {
  desktop: '2560px',
  laptop: '1024px',
  laptopL: '1440px',
  mobileL: '426px',
  mobileM: '376px',
  mobileS: '320px',
  tablet: '768px',
};

const device = {
  desktop: `(min-width: ${size.desktop})`,
  desktopL: `(min-width: ${size.desktop})`,
  laptop: `(min-width: ${size.laptop})`,
  laptopL: `(min-width: ${size.laptopL})`,
  mobileL: `(min-width: ${size.mobileL})`,
  mobileM: `(min-width: ${size.mobileM})`,
  mobileS: `(min-width: ${size.mobileS})`,
  tablet: `(min-width: ${size.tablet})`,
};

const shadows = {
  dropShadowCard: '1px 2px 4px #BBDED7',
};

const defaultTheme = {
  android,
  colors,
  device,
  fonts,
  id,
  size,
  shadows,
};

export default defaultTheme;
